
version: '3'
services:
    traefik:
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '$PWD/traefik.toml:/traefik.toml'
            - '$PWD/acme.json:/acme.json'
        ports:
            - '80:80'
            - '443:443'
        container_name: traefik
        command: --docker
        labels:
                # change URL here
            - traefik.frontend.rule=Host:monitor.example.com
            - traefik.port=8080
        image: 'traefik:v1.6.4-alpine'
