defaultEntryPoints = ["http", "https"]
[web]
address = ":8080"
  [web.auth.basic]
  # use htpasswd -nb admin to generate your own password hash
  users = ["admin:myhtpasswdkey"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
[acme]
# use your email address here
email = "mail@email.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
